name: inpost-home-assignment-web

services:
  selenium-hub:
    image: selenium/hub:4.23.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:127.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:128.0
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  tests:
    container_name: selenium-tests
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    command: sh -c "mvn clean test -q -Dtest=WebTestRunner -DdriverType=remote -DgridUrl=http://selenium-hub:4444/wd/hub || true && mvn allure:report -q"
